version: "3.9"

services:
  minio:
    image: minio/minio:RELEASE.2025-01-11T06-04-19Z
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    networks: [lakehouse]

  mc-init:
    image: minio/mc:RELEASE.2025-01-07T09-58-17Z
    container_name: mc-init
    depends_on: [minio]
    entrypoint: ["/bin/sh","-c"]
    command: >
      "mc alias set local http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD} &&
       mc mb --ignore-existing local/${S3_BUCKET} &&
       mc anonymous set download local/${S3_BUCKET} &&
       echo 'MinIO ready' && sleep 1"
    networks: [lakehouse]

  spark-master:
    image: bitnami/spark:3.5.1
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
    ports:
      - "7077:7077"
      - "8080:8080"
    volumes:
      - ./spark/conf:/opt/bitnami/spark/conf
      - ./jobs:/opt/jobs
      - ./data:/opt/data
    networks: [lakehouse]

  spark-worker:
    image: bitnami/spark:3.5.1
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
    depends_on: [spark-master]
    ports:
      - "8081:8081"
    volumes:
      - ./spark/conf:/opt/bitnami/spark/conf
      - ./jobs:/opt/jobs
      - ./data:/opt/data
    networks: [lakehouse]

  superset:
    image: apache/superset:3.0.0
    container_name: superset
    environment:
      - SUPERSET_SECRET_KEY=${SUPERSET_SECRET_KEY}
    depends_on: [spark-master]
    ports:
      - "8088:8088"
    command: ["/bin/sh","-c","/app/docker/docker-bootstrap.sh && superset run -p 8088 -h 0.0.0.0"]
    networks: [lakehouse]

networks:
  lakehouse:
    driver: bridge

volumes:
  minio-data:
